version: '3.8'

services:
  # postgres:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: review
  #     POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: app_redis
    volumes:
      - app_redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      PORT: 8014
    ports:
      - 8014:8014
    volumes:
      - app_data:/data

volumes:
  app_data:
  app_redis_data: